export enum KEY_WORDS {
  HERO = 'Hero',

  POKER_HAND = 'Poker Hand',
  TABLE = 'Table',
  SEAT = 'Seat',
  IN_CHIPS = 'in chips',
  POSTS_SMALL_BLIND = 'posts small blind',
  POSTS_BIG_BLIND = 'posts big blind',
  STRADDLE = 'straddle',

  DEALT_TO = 'Dealt to',
  UNCALLED_BET = 'Uncalled bet',
  RETURNED_TO = 'returned to',
  ALL_IN = 'all-in',

  NEXT_STAGE = '***',

  HOLE_CARDS = '*** HOLE CARDS ***',
  FLOP = '*** FLOP ***',
  FIRST_FLOP = '*** FIRST FLOP ***',
  SECOND_FLOP = '*** SECOND FLOP ***',
  THIRD_FLOP = '*** THIRD FLOP ***',
  TURN = '*** TURN ***',
  FIRST_TURN = '*** FIRST TURN ***',
  SECOND_TURN = '*** SECOND TURN ***',
  THIRD_TURN = '*** THIRD TURN ***',
  RIVER = '*** RIVER ***',
  FIRST_RIVER = '*** FIRST RIVER ***',
  SECOND_RIVER = '*** SECOND RIVER ***',
  THIRD_RIVER = '*** THIRD RIVER ***',
  SHOWDOWN = '*** SHOWDOWN ***',
  FIRST_SHOWDOWN = '*** FIRST SHOWDOWN ***',
  SECOND_SHOWDOWN = '*** SECOND SHOWDOWN ***',
  THIRD_SHOWDOWN = '*** THIRD SHOWDOWN ***',
  SUMMARY = '*** SUMMARY ***',

  TOTAL_POT = 'Total pot',
  RAKE = 'Rake',
  JACKPOT = 'Jackpot',
  BINGO = 'Bingo',
  FORTUNE = 'Fortune',
  TAX = 'Tax',

  BOARD = 'BOARD',
  HAND_WAS_RUN = 'Hand was run',
}
